import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";
import Counter from "@/components/Counter";
import UserForm from "@/components/UserForm";

export default function Home() {
  return (
    // Fragment - Envolve as tags que contém o conteúdo do site
    <>

      <Head>  
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Hello Word! Meu primeiro site em React!</h1>
        <Welcome/>
        <Welcome/>
        <Welcome/>
        <User/>
        {/* Passando props para os components */}
        <Description city="Registro" age={18} email="diego@amil.com" />
        {/* Componente com desestruturação de props */}
        <Pet name="Rex" breed="Pitbull" age={3} />
        <br/>
        {/* Importando o contador (utilizando estados) */}
        <Counter/>
        <br/>
        <UserForm/>
      </main>
    </>
  );
}
